
import { GoogleGenAI, Type } from "@google/genai";
import { StockPoint, AIProcessingResult, AIProvider } from "../types";

const API_KEY = process.env.API_KEY || "";

export class GeminiProvider implements AIProvider {
  name = "Gemini Flash";
  private ai = new GoogleGenAI({ apiKey: API_KEY });

  async generateArt(data: StockPoint[]): Promise<AIProcessingResult> {
    const dataStr = JSON.stringify(data);
    
    // Step 1: Manager AI Orchestration (Text Processing)
    const textResponse = await this.ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `You are the Lead Manager AI for Lake9.com. 
      Analyze this stock data: ${dataStr}. 
      Task your sub-AIs: 
      1. CurveGen: Create a simple mathematical expression representing the trend.
      2. Doppelganger: Identify a real-world physical object (e.g. a car fender, a mountain range, an animal's spine) that mirrors this curve shape. 
      3. Narrative: Create a short viral-ready summary.
      
      Provide a JSON response.`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            summary: { type: Type.STRING },
            doppelgangerPrompt: { type: Type.STRING, description: "Detailed prompt for image generation of the matching object" },
            mathExpression: { type: Type.STRING },
            visualNarrative: { type: Type.STRING }
          },
          required: ["summary", "doppelgangerPrompt", "mathExpression", "visualNarrative"]
        }
      }
    });

    const parsed = JSON.parse(textResponse.text);

    // Step 2: Image Generation (Visualizing the Doppelganger)
    // We use the doppelgangerPrompt generated by the Flash model to feed into the image model
    const imageResponse = await this.ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { text: `Create a sleek, artistic, 3D rendered visualization of ${parsed.doppelgangerPrompt}. It should look like high-end product design, minimalist, with a chrome or obsidian finish. 4K resolution, cinematic lighting.` }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9"
        }
      }
    });

    const imageUrls: string[] = [];
    for (const part of imageResponse.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        imageUrls.push(`data:image/png;base64,${part.inlineData.data}`);
      }
    }

    return {
      summary: parsed.summary,
      doppelgangerPrompt: parsed.doppelgangerPrompt,
      mathExpression: parsed.mathExpression,
      imageUrls: imageUrls.length > 0 ? imageUrls : ["https://picsum.photos/800/450"],
      visualNarrative: parsed.visualNarrative
    };
  }
}
